language: go

go:
  - "1.x"
  - "master"

install:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure -v

after_success:
  - $GOPATH/src/github.com/clmul/cutevpn/tools/pack.sh

deploy:
  provider: releases
  api_key:
    secure: DKHe+kCSyG+UADB7klAdO80hBuJ2pzZmTr4Xh5URfwbtLnTgaPZQyKI/UelstxotPvIhN+ttqCLQ7sa5zqD9gOda+S2kurdMNduhP4g+Gje2CRCqzkrXMlhfiWLYty64rwz8whfbyL8bPrRqzhaw6HDwu4kRXdG/zfy/xGn2q8Aq7SzO5qCOhTLUi+tYaDovJqoJFXL7Hts8BRLd2ph46+iDhlTQcc1uXo+lm4o7UWC2uR63+hewxLBhX2kWhMTbOtWQ5R0JoF+URXL4p+MNtODay+BR8OJ6IoRg3tXCtFC7ebO+MTlEDGrd02Qql1ER4peZ50RnXZKHMZOJREFWFlg2jhZcK3t+tUcppWOelMuuUKCvXQ6JCbwPZmWNFncvp4GDMb5dAo3W3fSGGc5JkIwTfpVHfqbY1gj3CvwAPc9YFSOuKUN+cK2Ijx3/Xg+Op5mg8xxBtGMuZTelH8qbrzPIewV1OehblwLSgcEJ2OJti1mqxyUtSNGsmGbXCNhRkABLP5XUd1ymoo7vXgtpgEPjsENPOC9PQnKv5XnD6LXCXEBZpeLGaXR18UYvw+1LNHQfTFFRnt+Uyz+pU6VqABALxojQfZqHFpXmIoAKZu3M4kcH1NwvOaOZZNp/2k95/o0w/vIWIUVEd9Go/AoC3w1K2JdxcVfXytc6aZEMr0I=
  file: $GOPATH/src/github.com/clmul/cutevpn/cutevpn/*.tar.gz
  file_glob: true
  skip_cleanup: true
  on:
    condition: $TRAVIS_GO_VERSION = 1.x
    tags: true
    repo: clmul/cutevpn
